name: Auto Close Security Issues
on:
  issues:
    types: [opened]
jobs:
  auto-close:
    runs-on: ubuntu-latest
    steps:
      - name: Auto close security-related issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const keywords = ["security", "vulnerability", "exploit", "xss", "sql injection", "cve"];
            const title = context.payload.issue.title.toLowerCase();
            const body = context.payload.issue.body ? context.payload.issue.body.toLowerCase() : "";
            if (keywords.some(k => title.includes(k) || body.includes(k))) {
              // Post a comment
              await github.rest.issues.createComment({
                issue_number: context.payload.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: ":Thanks for reporting a potential security issue!\n\nFor security-related reports, please **do not use public issues**.\n\n:lock: You can report vulnerabilities via:\n- :e-mail: Email: **hello@weam.ai**\n- :page_facing_up: Security Policy: [SECURITY.md](../SECURITY.md)\n\nThis issue has been closed automatically to protect sensitive information. We’ll respond quickly through the private channels above."
              });
              // Close the issue
              await github.rest.issues.update({
                issue_number: context.payload.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "closed"
              });
            }